config/routes.rb
Rails.application.routes.draw do

  get 'boats/index'

  get 'boats/new'

  get 'boats/edit'

  get 'boats/show'

  get 'boats/destroy'

  devise_for :users
  resources :boats
  resources :jobs 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root to: 'jobs#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boat.rb
class Boat < ApplicationRecord
  validates :name, uniqueness: true
  has_and_belongs_to_many :jobs
  belongs_to :user
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
end

app/models/job.rb
class Job < ApplicationRecord
  has_and_belongs_to_many :boats
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :boats
  has_many :jobs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  before_action :authenticate_user!

  def index
    @boats = Boat.all
  end

  def show
    @boat = Boat.find_by_id(params[:id])
  end

  def new
    @boat = Boat.new
  end

  def create
    @boat = Boat.new(boat_params)
    @boat.user_id = current_user.id
    if @boat.save
      redirect_to @boat
    else
      render 'new'
    end
  end

  def update
    @boat = Boat.find_by_id(params[:id])
    if @boat.update(boat_params)
      redirect_to @boat
    else
      render 'edit'
    end
  end

  def edit
    find_params
  end


  def destroy
    find_params
    @boat.destroy

    redirect_to @boat
  end

  private

  def boat_params
    params.require(:boat).permit(:name, :location, :containers, :avatar)
  end

  def find_params
    @boat = Boat.find_by_id(params[:id])
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def edit
    find_params
    @boats = Boat.all
  end

  def new
    @job = Job.new
  end

  def create
    @job = current_user.jobs.new(job_params)
    if @job.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @job = Job.find_by_id(params[:id])
    if @job.update(job_params)
      redirect_to @job
    else
      render 'edit'
    end
  end

  def destroy
    find_params
    @job.destroy
    redirect_to root_path
  end

  private

  def job_params
    params.require(:job).permit(:description, :origin, :destination, :cost, :containers, :boat_ids, boat_ids:[])
  end

  def find_params
    @job = Job.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/job_helper.rb
module JobHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/boats/edit.html.erb
<h1>Edit This Boat ⛵</h1>

<% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@boat.errors.count, "error") %> prohibited
        this boat from being saved:
      </h2>
      <ul>
        <% @boat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for @boat do |f| %>
<h4> Name </h4>
<%= f.text_field :name %>
<h4> Location </h4>
<%= f.select :location, ['Philadelphia', 'New York', 'Boston', 'Miami', 'Portland']%>
<h4> Containers Available </h4>
<%= f.number_field :containers %>
<h4> Boat Avatar </h4>
<%= f.file_field :avatar %>
<br>
<%= f.submit %>
<% end %>

app/views/boats/index.html.erb
<h1>All ya Boats ⛵</h1>

<% if @boats.empty? %>
  <h3> No boats yet </h3>
  <% end %>


<% @boats.each do |boat| %>
  <h3>Name: </h3>
  <%= boat.name %>
  <h3>Location: </h3>
  <%= boat.location %>
  <h3>Containers Available: </h3>
  <%= boat.containers %>
  <h3>Boat: </h3>
  <%= image_tag boat.avatar.url(:thumb) %>
  <br>
  <%= link_to 'See', boat_path(boat) %>
<% if current_user.id == boat.user_id %>
<%= link_to 'Edit', edit_boat_path(boat) %>
<%= link_to 'Delete', boat_path(boat),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
        <br>
<% end %>
<% end %>

<%= link_to 'New Boat', boats_new_path%>

app/views/boats/new.html.erb
<h1>New Boat ⛵</h1>

<% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@boat.errors.count, "error") %> prohibited
        this boat from being saved:
      </h2>
      <ul>
        <% @boat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for @boat do |f| %>
<h4> Name </h4>
<%= f.text_field :name%>
<h4> Location </h4>
<%= f.select :location, ['Philadelphia', 'New York', 'Boston', 'Miami', 'Portland']%>
<h4> Containers Available </h4>
<%= f.number_field :containers %>
<h4> Boat Avatar </h4>
<%= f.file_field :avatar %>
<br>
<%= f.submit %>
<% end %>

app/views/boats/show.html.erb
<h1>This Boat ⛵</h1>

<h3>Name:</h3>
<i><%= @boat.name %></i>
<h3>Location:</h3>
<i><%= @boat.location%></i>
<h3>Number of Available Containers:</h3>
<i><%= @boat.containers%></i>
<br>
<%= image_tag @boat.avatar.url(:medium) %>

<h4>Jobs:</h4>
<% if @boat.jobs.empty? %>
<h3>No Jobs Yet</h3>
<% end %>
  <ul>
    <% @boat.jobs.each do |job| %>
      <li> <%= link_to job.created_at, job_path(job) %></li>
    <% end %>
  </ul>


<% if current_user.id == @boat.user_id %>
<%= link_to 'Edit', edit_boat_path(@boat) %>
<%= link_to 'Delete', boat_path(@boat),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/jobs/edit.html.erb
<h1>Edit this Job 📦</h1>



<% if @job.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@boat.errors.count, "error") %> prohibited
        this boat from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%= form_for @job do |f| %>
<% if current_user.id == @job.user_id %>
  <h4> Job </h4>
  <%= f.text_area :description, :minlength => 50%>
  <h4> Origin </h4>
  <%= f.text_field :origin%>
  <h4> Destination </h4>
  <%= f.text_field :destination%>
  <h4> Cost </h4>
  <%= f.number_field :cost, :min => 1000%>
  <h4> Containers </h4>
  <%= f.number_field :containers%>
  <% end %>
  <h4> Boats Available For Job </h4>
  <%= collection_check_boxes(:job, :boat_ids, current_user.boats, :id, :name, checked: true)%>
  <br>
  <% if current_user.boats.empty? %>
  <p>Uh oh! You don't have any boats to add to this job.</p>
  <% else %>
  <br>
  <%= f.submit %>
  <% end %>
<% end %>

app/views/jobs/index.html.erb
<h1>All the Jobs 📦</h1>


<% if @jobs.empty? %>
  <p> No boats yet </p>
  <% end %>

<% @jobs.each do |p| %>
<ul>
  <li><%= link_to p.created_at, p %>
    <% if current_user.id == p.user_id %>
    <%= link_to 'Delete', job_path(p),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
    <% end %>
  </li>
</ul>
<% end %>

<%= link_to 'New Job', new_job_path%>

app/views/jobs/new.html.erb
<h1>New Job 📦</h1>


<% if @job.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@job.errors.count, "error") %> prohibited
        this boat from being saved:
      </h2>
      <ul>
        <% @job.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<%= form_for @job do |f| %>
  <h4> Job </h4>
  <%= f.text_area :description, :minlength => 50%>
  <h4> Origin </h4>
  <%= f.select :origin, ['Philadelphia', 'New York', 'Boston', 'Miami', 'Portland']%>
  <h4> Destination </h4>
  <%= f.select :destination, ['Philadelphia', 'New York', 'Boston', 'Miami', 'Portland']%>
  <h4> Cost </h4>
  <%= f.number_field :cost, :min => 1000%>
  <h4> Containers </h4>
  <%= f.number_field :containers%>
  <%= f.submit %>
<% end %>

app/views/jobs/show.html.erb
<h1>This Job 📦</h1>

<h4>Containers Needed for This Job 📦:</h4>
<%= @job.containers %>

<h4>Boats on this Job</h4>
  <ul>
    <% @job.boats.each do |boat| %>
      <li> <%= boat.name %> will supply <%= boat.containers %> containers</li>
    <% end %>
  </ul>
  <% @jobcontainers = @job.containers %>
  <% @all = 0; %>
  <% @job.boats.each do |boat| %>
    <% @all = @all + boat.containers %>
  <% end %>
  <% @containers_needed = @jobcontainers - @all %>

  <p> Total Boat Containers: </p>
  <%= @all %>
  <p> Containers Still Needed: </p>
  <% if @containers_needed < 0 %>
  <p> 0 </p>
  <% else %>
  <%= @containers_needed %>
  <% end %>

  <h3>Job Status: </h3>
  <% if @containers_needed < 0 %>
  <p> Completed ✅ </p>
  <% else %>
  <p> Boats Still Needed ⛵ </p>
  <% end %>


<h3>Job Description</h3>
<%= @job.description %>
<br>
<h3>Job Origin</h3>
<%= @job.origin %>
<br>
<h3>Job Destination</h3>
<%= @job.destination %>
<br>
<h3>Job Cost</h3>
<%= @job.cost %> 💰
<br>

<% if @containers_needed > 0 %>
<!-- if the boats have enough containers for the job, you can't add any more boats -->
<%= link_to 'Add a Boat', edit_job_path(@job) %>
<% end %>
<% if current_user.id == @job.user_id %>
<%= link_to 'Delete', job_path(@job),
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsShipped</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lato' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Lobster' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Jobs', '/' %>
        <%= link_to 'Boats', '/boats' %>
        <%= link_to 'Logout', destroy_user_session_path,
          method: :delete, data: {confirm: 'are you sure??'}
         %>
       <% end %>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>